preload = ~/dotfiles/wallpaper/anime-girls-catzz-computer-doll-Serial-Experiments-Lain.jpg
preload = ~/dotfiles/wallpaper/pink-moon.png

wallpaper = DP-1,~/dotfiles/wallpaper/anime-girls-catzz-computer-doll-Serial-Experiments-Lain.jpg
wallpaper = HDMI-A-1,~/dotfiles/wallpaper/pink-moon.png

